name: smart_attend_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animations: ^2.0.11
  camera: ^0.11.0+1
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1+1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  simple_animations: ^5.0.2
  socket_io_client: ^2.0.3+1
  sprung: ^3.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/Segoe_UI.ttf
        - asset: assets/fonts/Segoe_UI_Bold.ttf
        - asset: assets/fonts/Segoe_UI_Italic.ttf
        - asset: assets/fonts/Segoe_UI_Bold_Italic.ttf
